### PR TITLE
fix: add newline to the end of each course in the index

### PR DESCRIPTION
**Pull request by JacobLinCool**
fix the homepage index indentation.

### CODE REVIEW

**Comment by JacobLinCool** [comment]
@skyhong2002 https://github.com/NTNU-CSIE/course-resource/pull/6/commits/65511a2dcacdc9a2dbe1fc649afaa8788c190d93

如果要加的話，我比較想用 all-contributors 誒

**Comment by skyhong2002** [comment]
好ㄚ那你加完我再 Review

**Comment by JacobLinCool** [comment]
@all-contributors please add @JacobLinCool @skyhong2002 @Beck049 for content and review

**Comment by JacobLinCool** [comment]
我應該等 merge 完再加 Contributors。

@skyhong2002 PR Ready

**Review by skyhong2002 — APPROVED** [review]
LGTM!

**Pull request merged**
